kind: Deployment
apiVersion: apps/v1
metadata:
  # set your lab user name
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      # set your lab user name
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        # set your lab user name
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: {{ .Chart.Name }}-html
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html  # this will mount the index.html file to the application location
          resources: {}
          terminationMessagePath: /dev/termination-log

          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/readiness  # this checks the application URL path
              port: {{ .Values.containers.containerPort }} # Application listening port
              scheme: HTTP
            initialDelaySeconds: 1  # wait time before testing
            timeoutSeconds: 1       # timeout for each probe
            periodSeconds: 10       # interval between checks
            successThreshold: 1
            failureThreshold: 3

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  revisionHistoryLimit: 10
